### ISSUE TITLE
!global fails grunt from compiling css

### ISSUE THREAD

**Issue by daigofuji** [daigofuji/jekyll-foundation-5-starter#1]
I get this error message when I run `grunt` after `foundation update`

> Running "sass:dist" (sass) task
> Warning: bower_components/foundation/scss/foundation/functions:13: error: error reading values after $modules
> Use --force to continue.

I've edited above file, but since it is a bower installed file, when I run update in the future, I need to remember to change it back...

**Comment by eah13** [comment]
Looks like your most recent commit introduced this bug again.  Removing the bang global fixes it.

**Comment by daigofuji** [comment]
Ooops, thanks!
