### ISSUE TITLE
Should bower_components be in .gitignore?

### ISSUE THREAD

**Issue by pmackay** [daigofuji/jekyll-foundation-5-starter#13]
I found I had to remove the entry of `bower_components` in `.gitignore` to allow those files to be committed to a new project (I had a scenario where I copied the project contents over to another project). It doesnt seem quite right that they are present but ignored?

**Comment by daigofuji** [comment]
This perhaps explains why it was working on my local but not yours... I removed it from gitignore and updated the contents of this repo, but perhaps I should be using npm shrinkwrap, according to [npm documentation](https://docs.npmjs.com/misc/faq#should-i-check-my-node-modules-folder-into-git). Please test and see if you can run `grunt`. Thanks!

**Comment by pmackay** [comment]
Reading http://addyosmani.com/blog/checking-in-front-end-dependencies/ there are pros and cons each way. Perhaps in this case, as Jekyll is often used in GH Pages, which wouldnt allow to run `bower install`, checking them in is the right approach, in which case removing that dir from `.gitignore` makes sense. And it says you cannot shrinkwrap bower.json yet...

**Comment by daigofuji** [comment]
Thanks @pmackay 
For now I will leave both npm_modules and bower_components in the repo. :+1:
