### ISSUE TITLE
Hamburger Menu Does not work on Mobile Safari or Chrome on iOS

### ISSUE THREAD

**Issue by evanroane** [daigofuji/jekyll-foundation-5-starter#3]

**Comment by daigofuji** [comment]
You are right. Tested on my freinds' iPhone 5S and it is not working. Investigating, but if anyone have a fix, I could use your help!

**Comment by daigofuji** [comment]
This seem to have fixed it! https://github.com/daigofuji/jekyll-foundation-5-starter/commit/6223fc38792b109a9baacb0f239b1aa70d500d6e
