### ISSUE TITLE
_settings.scss changes don't work?

### ISSUE THREAD

**Issue by noxidsoft** [daigofuji/jekyll-foundation-5-starter#8]
Hi,

Thanks for a great primer for Jekyll/Zurb.

I made a couple of changes to the _settings.scss file and re-compiled but they don't take/reflect changes?

Doing this:
$row-width: rem-calc(1400);
$primary-color: #ff9641; //was #8bad93 - green to orange

Then tried:
$ jekyll build/serve

and/or:
$ grunt / grunt build

**Comment by daigofuji** [comment]
Hi, 
Mmm. That is strange. 
Let me check to make sure I am not missing anything.

**Comment by thovo** [comment]
I met the same issue, sent you an email about it.
I changed _settings.scss and _custom.scss but nothing happened with style.css
I hope you can check it soon!

**Comment by S1SYPHOS** [comment]
No stylesheet is created so the old one is used so no change to your scss files applies, seems to be a problem with node-sass / grunt-sass, I'd suggest you update your dependencies which worked for me. I'll send a pull request asap (which could take a while) :-)

**Comment by thovo** [comment]
I believe you already committed all of your node_modules, which is too much unnecessary files . Could you tell us clearly what dependencies did you update?

**Comment by S1SYPHOS** [comment]
Take a look at package.json and there you go - all of them, but the one's in question are grunt-sass, node-sass and grunt.

**Comment by daigofuji** [comment]
To recap, the reason we couldn't compile css from scss was that I was using very old version of grunt sass and Node Sass

https://github.com/daigofuji/jekyll-foundation-5-starter/blob/gh-pages/package.json

WAS

```
{
  "name": "foundation-libsass-template",
  "version": "0.0.1",
  "devDependencies": {
    "node-sass": "~0.7.0",
    "grunt": "~0.4.1",
    "grunt-contrib-watch": "~0.5.3",
    "grunt-sass": "~0.8.0"
  }
}
```

IS now, Thanks to @S1SYPHOS 

```
{
  "name": "foundation-libsass-template",
  "version": "0.0.1",
  "devDependencies": {
    "node-sass": "^2.1.1",
    "grunt": "~0.4.5",
    "grunt-contrib-watch": "~0.6.1",
    "grunt-sass": "^0.18.1"
  }
}
```

Thank you so much and I will close this issue.

**Comment by S1SYPHOS** [comment]
Glad to help!

**Comment by thovo** [comment]
Glad to see it is good now :+1:
